from . import sale_order
from . import payment_plan
from . import res_partner
from . import industry_sector
from . import state_history
from . import account_move
from . import base_substate
from . import payment_link_wizard
from . import url_shortner