# See LICENSE file for full copyright and licensing details.

{
    'name': 'Setu Dialer',
    'version': '16.0.1.0.0',
    'category': '',
    'license': 'LGPL-3',
    'summary': 'Setu Dialer',
    'depends': ['base', 'hr_attendance', 'mail', 'scs_project_extended'],
    'data': [
        'data/report_column_demo.xml',
        'data/email_templates.xml',
        # 'data/fetch_inbound_cron.xml',
        'security/groups.xml',
        'views/res_users_views.xml',
        'security/ir.model.access.csv',
        'security/dashboard_overview_rules.xml',
        'security/call_detail_rules.xml',
        'views/disposition_list_configuration_views.xml',
        'views/campaigns_list_views.xml',
        'views/dispo_list_name_views.xml',
        'views/lead_list_data_views.xml',
        'views/report_column_views.xml',
        'views/lead_data_lead_views.xml',
        'views/fetch_lead_user_views.xml',
        'views/lead_call_history_views.xml',
        'views/lead_dnd_views.xml',
        'views/lead_callback_info_views.xml',
        'views/res_config_settings_view.xml',
        'views/call_detail_record_view.xml',
        'views/lead_call_merged_views.xml',
        'views/lean_manual_lead_views.xml',
        'views/hr_employee_views.xml',
        'views/hr_manual_attendance_menu.xml',
        'views/dashboard_overview_views.xml',
        'views/lead_closer_calling_views.xml',
        'views/closer_name_views.xml',
        'views/branch_manager_assignment_views.xml',
        'views/lead_management_views.xml',
        'views/csv_lead_status_view.xml',
        'views/csv_lead_reason_views.xml',
        'views/pysical_meeting_views.xml',
        'views/hbad_data_info_views.xml',
        'views/hbab_data_status_views.xml',
        'views/agreement_views.xml',
        'views/offline_hbab_service_views.xml',
        'views/offline_hbab_status_views.xml',
        # 'views/res_users_views.xml',
        'views/sale_order_csv_import_views.xml',
        # 'views/disposition_queue_views.xml',
        # 'views/disposition_master_views.xml',
        'wizard/campaidns_upload_wizards_views.xml',
        'wizard/lead_list_export_wizard_views.xml',
        'wizard/lean_manual_upload_views.xml',
        'wizard/lead_transfer_wizard_views.xml',
        'wizard/update_lead_list_wizard_views.xml',
        'wizard/assign_closer_wizard_views.xml',
        'wizard/lead_upload_wizard_view.xml',
        'wizard/bulk_update_user_wizard_view.xml',
        'wizard/pysical_meeting_wizard_views.xml',
        'wizard/hbad_data_import_wizard_views.xml',
        'wizard/agreement_feedback_wizard_views.xml',
        'wizard/project_task_wizard_views.xml',
        # 'wizard/delete_leads_wizard.xml',
        'views/setu_dialer_menuitem.xml',
    ],
    
    'assets': {
        'web.assets_backend': [
            # 'setu_dialer/static/src/js/disposition_submit.js',
            'setu_dialer/static/src/css/dashboard.css',
            'setu_dialer/static/src/css/lead_tree_style.css',
            # 'setu_dialer/static/src/css/custom_header.css',
        ]
    },

    # 'assets': {
    #     'web.assets_backend': [
    #         '/setu_dialer/static/src/xml/dashboard_overview_assets.xml',
    #     ],
    # },

    'installable': True,
}
