from . import res_users
from . import campaigns_list
from . import disposition_list_configuration
from . import dispo_list_name
from . import lead_list_data
from . import report_column
from . import lead_data_lead
from . import fetch_lead_user
from . import lead_call_history
from . import lead_callback_info
from . import res_config_settings
from . import call_detail_record
from . import lead_call_merged
from . import lean_manual_lead
from . import inbound_call_temp
from . import hr_employee
from . import dashboard_overview
from . import closer_name
from . import lead_closer_calling
from . import branch_manager_assignment
from . import lead_management
from . import csv_lead_status
from . import csv_lead_reason
from . import pysical_meeting
from . import hbad_data_info
from . import hbab_data_status
from . import agreement
from . import offline_hbab_service
from . import offline_hbab_status
from . import disposition_queue
from . import disposition_master